modLoader = "javafml"
loaderVersion = "[66,)"
license = "MIT"

[[mods]]
modId = "mcpersist"
version = "${version}"
displayName = "MCPersist"
logoFile = "mcpersist_icon.png"
authors = "5TN1rcZRS79VAEFuUCRB"
credits = "Based on e4mc by skyevg"
displayURL = "https://github.com/5TN1rcZRS79VAEFuUCRB/MCPersist"
description = '''
e4mc, but your world keeps running after you leave. Based on e4mc by skyevg.
'''

[[dependencies.mcpersist]]
modId = "minecraft"
mandatory = true
versionRange = "[26.3,)"
ordering = "NONE"
side = "BOTH"
