org.gradle.jvmargs=-Xmx2048M

minecraft_version=26.3
fabric_loader_version=0.19.5
fabric_api_version=0.161.0+26.3

archives_base_name=mcpersist
mod_version=2.0.0-alpha.1
maven_group=link.e4mc

quic_version=0.0.74.Final.e4mc.1
iroh_java_version=0.1.1
dirs_version=26
neoforge_version=26.3.0.23-beta
forge_version=66.0.4
