pluginManagement {
    repositories {
        maven { url "https://maven.fabricmc.net/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.minecraftforge.net/" }
        maven { url "https://maven.neoforged.net/releases/" }
        gradlePluginPortal()
    }
}

include("common")
include("fabric")
// Fabric only for now; the forge and neoforge projects are kept for later.
// include("forge")
// include("neoforge")

rootProject.name = "mcpersist"
